# Generated by Django 4.2.26 on 2025-12-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkies', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
