# Generated by Django 4.2.26 on 2025-12-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekkies', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
