# Generated by Django 4.2.26 on 2025-12-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkies', '0008_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
    ]
